### ISSUE TITLE
Code Licensing

### ISSUE THREAD

**Issue by amnotbananaama** [mrburger/TouchBar#1]
Hello, I stumbled across your mod out of curiosity if anyone had done this before. I was curious to try and port this to the [Fabric modloader](https://www.fabricmc.net).

Would it be possible for you to add a permissive license to this code? Thank you for your consideration.

**Comment by mrburger** [comment]
Hello,

honestly, I had forgotten about this personal project. It sort of hit a dead-end when I realized the rendering was taking ages. I can give and am giving you permission to use my code WITH credit given to my work. Thanks for asking!
